import pandas as pd

data = [
["project-id","project.project_id","Project","100% duplicate, naming difference only"],
["Project ID","project.project_id","Project","100% duplicate"],
["Internal project code","project.project_id","Project","100% duplicate, generated at different stage"],
["experiment-id","project.experiment_id","Project","100% duplicate"],
["Experiment ID","project.experiment_id","Project","100% duplicate"],
["experiment name","project.experiment_name","Project","100% duplicate"],
["Experiment title","project.experiment_name","Project","100% duplicate"],
["Plot","plot.plot_id","Plot","Same entity as Plot number, different stage"],
["Plot number","plot.plot_id","Plot","Same entity as Plot"],
["GPS coordinates sampling points","location.sampling_point_gps","Location","Sampling-point level GPS"],
["Farm address / GPS coordinates","location.farm_gps_coordinates","Location","Farm-level GPS"],
["location description","location.location_description","Location","Duplicate of Approximate farm location"],
["Approximate farm location","location.location_description","Location","Duplicate of location description"],
["altitude","location.elevation_m","Location","100% equivalent to Elevation"],
["Elevation","location.elevation_m","Location","100% equivalent to altitude"],
["date","sampling.sampling_date","Sampling","Sampling date"],
["Application date","sampling.sampling_date","Sampling","Same time field"],
["author","sampling.sampler","Sampling","Different role name, same meaning"],
["sampling coordinator","sampling.sampler","Sampling","Different role name, same meaning"],
["Responsible person","sampling.sampler","Sampling","Different role name, same meaning"],
["temperature","weather.air_temperature_c","Weather","Air temperature"],
["Soil temperature","weather.soil_temperature_c","Weather","Soil temperature, not identical to air"],
["rainfall","weather.rainfall_mm","Weather","Same data source as weather station"],
["Nearby weather station (public)","weather.weather_data_source","Weather","Weather data source"],
["Soil texture","soil_properties.texture","Soil","Repeated across indicator groups"],
["Texture","soil_properties.texture","Soil","Repeated across indicator groups"],
["Bulk density","soil_properties.bulk_density","Soil","Repeated across indicator groups"],
["pH","soil_properties.ph","Soil","Repeated across indicator groups"],
["Electrical conductivity","soil_properties.electrical_conductivity","Soil","Duplicate of salinity (EC)"],
["Salinity; specific EC","soil_properties.electrical_conductivity","Soil","Duplicate of EC"],
["Organic C","soil_properties.organic_carbon","Soil","Duplicate of TOC / Organic matter"],
["TOC","soil_properties.organic_carbon","Soil","Duplicate of Organic C"],
["Organic matter (POM & MAOM)","soil_properties.organic_carbon","Soil","Same indicator, different expression"],
["Total N","soil_properties.total_nitrogen","Soil","Duplicate of TON"],
["TON","soil_properties.total_nitrogen","Soil","Duplicate of Total N"],
["Available P","soil_properties.available_phosphorus","Soil","Duplicate of P"],
["P","soil_properties.available_phosphorus","Soil","Duplicate of Available P"],
["CEC","soil_properties.cec","Soil","Duplicate of exchangeable cations"],
["CEC and exchangeable cations (Mg, Ca, Na, K)","soil_properties.cec","Soil","Same indicator"],
["Water holding capacity","soil_properties.water_holding_capacity","Soil","Duplicate of Water retention"],
["Water retention","soil_properties.water_holding_capacity","Soil","Duplicate of Water holding capacity"],
["Enzyme activity","soil_biology.enzyme_activity","Soil biology","Duplicate of Enzymatic activity"],
["Enzymatic activity (dehydrogenase)","soil_biology.enzyme_activity","Soil biology","Same indicator"],
["Microbial abundance","soil_biology.microbial_abundance","Soil biology","Repeated"],
["Microbial diversity (bacteria, archaea, fungi)","soil_biology.microbial_diversity","Soil biology","Repeated"],
["Ecosystem engineers (macrofauna/earthworms)","soil_biology.macrofauna","Soil biology","Repeated"],
["Ploughing","management.tillage","Management","100% match with T3.2 question"],
["Fertilisation","management.fertilization","Management","Overlaps with soil amendment question"],
["Plant protection agents","management.plant_protection","Management","Covers pesticide-related questions"],
["Grazing system","management.grazing_system","Management","High match with T3.2 questions"],
["Crop rotation","management.crop_rotation","Management","100% duplicate"],
]

df = pd.DataFrame(data, columns=["Original field","Unified field key","Category","Notes"])
out = "Duplicate_to_Unified_Field_Mapping.xlsx"
df.to_excel(out, index=False)
out
